spring:
   application:
      name: tayaservice
server:
   port: 8080

---
spring:
   profiles: dev
   application:
      name: tayaservice
server:
   port: 9090

---
spring: 
   profiles: prod
   application:
      name: tayaservice
server: 
   port: 4431